# Generated by Django 4.2.15 on 2024-12-29 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanasu', '0003_choice_delete_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
