# Generated by Django 4.2.15 on 2025-01-02 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hanasu', '0005_quiz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
